version: '3.8'

services:
  postgres:
    image: postgres:14.7
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: rsupport_admin
      POSTGRES_PASSWORD: r_support123!@#
      POSTGRES_DB: rsupport
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
